services:
  dlna:
    image: vladgh/minidlna:1.3.7
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000
      MINIDLNA_MEDIA_DIR: /media
      MINIDLNA_FRIENDLY_NAME: NAS
      TZ: Europe/Vienna
    volumes:
      - ./media:/media
    deploy:
        resources:
            limits:
              memory: 1G
