services:
  mc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      SERVER_NAME: "axi92's Server"
      EULA: true
      ICON: 'https://avatars.githubusercontent.com/u/1394837?v=4'
      OVERRIDE_ICON: true
      MAX_PLAYERS: 8
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: 'https://www.curseforge.com/minecraft/modpacks/tnp-limitless-8'
      MAX_WORLD_SIZE: 10000
      ENABLE_COMMAND_BLOCK: false
      FORCE_GAMEMODE: true
      MODE: "survival"
      SNOOPER_ENABLED: false
      PVP: false
      ONLINE_MODE: true
      ALLOW_FLIGHT: true
      STOP_SERVER_ANNOUNCE_DELAY: 10
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      OPS: |
        axi92
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_CMDS_LAST_DISCONNECT: |-
        kill @e[type=minecraft:boat]
      RCON_CMDS_STARTUP:  |-
        gamerule doFireTick false
        gamerule keepInventory true
      MEMORY: 10G
      ENABLE_ROLLING_LOGS: true
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      # - ./downloads:/downloads
    dns:
      - 1.1.1.1
    deploy:
        resources:
            limits:
              memory: 10G
