services:
  grocy:
    image: linuxserver/grocy:4.2.0
    hostname: grocy
    container_name: grocy
    volumes:
      - ./config:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Vienna'
    ports:
      - 127.0.0.1:9283:80
    restart: unless-stopped
  barcodebuddy:
    image: f0rc3/barcodebuddy:v1.8.1.8
    hostname: barcodebuddy
    container_name: barcodebuddy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Vienna'
    ports:
      - 127.0.0.1:9284:80
    restart: unless-stopped