version: "3"

services:
  yt-dlp-web-ui:
    container_name: yt-dlp-web-ui
    hostname: yt-dlp-web-ui
    image: ghcr.io/marcopeocchi/yt-dlp-web-ui:v2.0.8
    ports:
      - "3033:3033/tcp"
    environment:
      TZ: 'Europe/Vienna'
    # Volumes store your data between container upgrades
    volumes:
      - './downloads:/downloads'
    restart: unless-stopped
